# Generated by Django 2.2.2 on 2019-06-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='plan',
        ),
    ]
