# Generated by Django 2.2.2 on 2019-06-09 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_status_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
