# Generated by Django 2.2.2 on 2019-06-09 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190609_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
