# Generated by Django 2.2.2 on 2019-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Plan1', 'plan1'), ('Plan2', 'plan2'), ('Plan3', 'plan3')], default='Plan1', max_length=5),
        ),
    ]
