# Generated by Django 2.2.2 on 2019-06-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190609_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.Plan'),
        ),
    ]
