# Generated by Django 2.2.2 on 2019-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20190609_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
