# Generated by Django 2.2.2 on 2019-06-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20190609_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='view',
            new_name='likes',
        ),
    ]
